
'use server';
/**
 * @fileOverview An AI agent for evaluating student essays using direct Groq API calls.
 */

import { z } from 'zod';

const EvaluateEssayFeedbackInputSchema = z.object({
  essayText: z.string(),
  topic: z.string(),
  academicLevel: z.enum(['High School', 'College', 'Graduate', 'Other', 'School Class 8-10', 'School Class 11-12', 'Undergraduate Year 1', 'Undergraduate Year 2', 'Undergraduate Year 3', 'Competitive Exams (UPSC)', 'Competitive Exams (JEE/NEET)', 'Competitive Exams (CAT/CLAT/SSC/NDA)']),
  wordLimit: z.string().optional(),
  question: z.string().optional(),
});
export type EvaluateEssayFeedbackInput = z.infer<typeof EvaluateEssayFeedbackInputSchema>;

const EvaluateEssayFeedbackOutputSchema = z.object({
  score: z.number().int().min(0).max(10),
  strengths: z.array(z.string()),
  weaknesses: z.array(z.string()),
  improvementSuggestions: z.array(z.string()),
  modelAnswerOutline: z.array(z.string()),
});
export type EvaluateEssayFeedbackOutput = z.infer<typeof EvaluateEssayFeedbackOutputSchema>;

export async function evaluateEssayFeedback(input: EvaluateEssayFeedbackInput): Promise<EvaluateEssayFeedbackOutput> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) throw new Error("GROQ_API_KEY is not set");

  const systemPrompt = `You are an expert academic mentor and essay evaluator. 
Your task is to provide comprehensive, constructive feedback on a student's essay. 
You must strictly return a JSON object following the schema provided. 

Key evaluation criteria:
- Relevance to the topic/question
- Structural integrity (Introduction, Body, Conclusion)
- Grammatical precision and academic vocabulary
- Depth of analysis and critical thinking

Schema:
{
  "score": number, // Overall score from 0-10 based on academic standards
  "strengths": ["string"], // List 3-4 specific strengths
  "weaknesses": ["string"], // List 3-4 specific areas needing refinement
  "improvementSuggestions": ["string"], // 3 actionable steps to improve this specific essay
  "modelAnswerOutline": ["string"] // 5-6 points outlining a high-scoring structural blueprint
}`;

  const userPrompt = `Evaluation Context:
- Academic Level: ${input.academicLevel}
- Topic: ${input.topic}
${input.question ? `- Specific Question: ${input.question}` : ''}
${input.wordLimit ? `- Target Word Limit: ${input.wordLimit}` : ''}

--- Student Essay Start ---
${input.essayText}
--- Student Essay End ---

Critically analyze the content above. Focus on providing mentorship that helps the student grow.`;

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.1-8b-instant',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.3,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Groq API Error: ${response.statusText}`);
  }

  const data = await response.json();
  const content = data.choices[0].message.content;

  try {
    const parsed = JSON.parse(content);
    return EvaluateEssayFeedbackOutputSchema.parse(parsed);
  } catch (e) {
    console.error("Failed to parse evaluation output:", content);
    throw new Error("Invalid evaluation data generated by AI.");
  }
}
