
'use server';
/**
 * @fileOverview A flow for generating academic assessments using direct Groq API calls.
 */

import { z } from 'zod';

const MCQSchema = z.object({
  question: z.string(),
  options: z.array(z.string()),
  correctAnswer: z.string(),
});

const FlashcardSchema = z.object({
  front: z.string(),
  back: z.string(),
});

const EssayPromptSchema = z.object({
  prompt: z.string(),
  modelAnswerOutline: z.array(z.string()),
});

const GenerateStudyAssessmentsInputSchema = z.object({
  studyMaterial: z.string(),
  assessmentTypes: z.array(z.enum(['MCQ', 'Flashcard', 'Essay', 'Mixed'])),
  academicLevel: z.string(),
  difficulty: z.enum(['Easy', 'Medium', 'Hard']),
  questionCount: z.number().int().min(1).max(20),
});
export type GenerateStudyAssessmentsInput = z.infer<typeof GenerateStudyAssessmentsInputSchema>;

const GenerateStudyAssessmentsOutputSchema = z.object({
  mcqs: z.array(MCQSchema).optional(),
  flashcards: z.array(FlashcardSchema).optional(),
  essayPrompts: z.array(EssayPromptSchema).optional(),
});
export type GenerateStudyAssessmentsOutput = z.infer<typeof GenerateStudyAssessmentsOutputSchema>;

export async function generateStudyAssessments(input: GenerateStudyAssessmentsInput): Promise<GenerateStudyAssessmentsOutput> {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) throw new Error("GROQ_API_KEY is not set");

  const systemPrompt = `You are an AI assistant specialized in creating diverse academic assessments.
Your task is to generate various types of assessments based on the provided study material and user specifications.
Format your response as a valid JSON object strictly following the output schema.
Schema:
{
  "mcqs": [{"question": "string", "options": ["string"], "correctAnswer": "string"}],
  "flashcards": [{"front": "string", "back": "string"}],
  "essayPrompts": [{"prompt": "string", "modelAnswerOutline": ["string"]}]
}`;

  const userPrompt = `Study Material:
"""
${input.studyMaterial}
"""

Assessment Configuration:
- Desired Assessment Types: ${input.assessmentTypes.join(', ')}
- Academic Level: ${input.academicLevel}
- Difficulty: ${input.difficulty}
- Number of Questions for each type: ${input.questionCount}

Instructions:
1. Carefully read the study material.
2. Generate assessments according to the specified types, academic level, difficulty, and question count.
3. Ensure all generated content is directly derived from or highly relevant to the provided study material.
4. For MCQs, provide at least 4 options.
5. For Flashcards, provide a clear front and concise back.
6. For Essay prompts, create a thought-provoking question and provide a bulleted outline of key points.
7. Return ONLY the JSON object.`;

  const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model: 'llama-3.1-8b-instant',
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.7,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    console.error("Groq API Error:", errorData);
    throw new Error(`Groq API Error: ${response.statusText}`);
  }

  const data = await response.json();
  const content = data.choices[0].message.content;
  
  try {
    const parsed = JSON.parse(content);
    return GenerateStudyAssessmentsOutputSchema.parse(parsed);
  } catch (e) {
    console.error("Failed to parse LLM output:", content);
    throw new Error("Invalid assessment data generated by AI.");
  }
}
